### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [ ]:
import numpy as np
quadrati = []
for i in range (10):
    quadrati.append(i**2)
print(quadrati)

quadrati=[i**2 for i in range (10)]
print(quadrati)
print("\n\n")

pari=[]
for i in range (10):
    if i%2==0:
        pari.append(i)
print(pari)

pari=[i for i in range (10) if i%2==0]
print(pari)


print("\n\n")
list=["Ciao", "a", "tutti"]
for i in range(len(list)):
    list[i]=list[i].upper()
print(list)

list=["Ciao", "a", "tutti"]
list=[parola.upper() for parola in list]
print(list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [ ]:
import numpy as np
vett=np.array([2,3,5,7])
print(vett)
len(vett)
vett.size
vett.dtype
vett=[]
vett = np.array([i for i in range(11) if i > 1 and all(i % d != 0 for d in range(2, i))])
print(vett)

False


[2, 3, 5, 7]

### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [25]:
a= np.arange(1,21)
b= a[:-1:]
c= a[::-1]
a,b,c

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
         3,  2,  1]))